services:
  web:
    build: ./php
    container_name: php-container
    ports:
      - "8082:80"
    volumes:
     - ./php:/var/www/html
    depends_on:
      - db
    networks:
      - net_devops_pfo_dos_part_dos   # <-- esta red está definida más abajo

  db:
    image: mysql:8.0.42 
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin234
      MYSQL_DATABASE: devops_pfo_dos_part_dos
      MYSQL_USER: alumnos
      MYSQL_PASSWORD: alumno234
    volumes:
      - db_data:/var/lib/mysql  # Uso en el servicio
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net_devops_pfo_dos_part_dos  # <-- esta red está definida más abajo


volumes:
  db_data:   # Declaración global


networks:  
  net_devops_pfo_dos_part_dos:   # <-- red definida correctamente
    driver: bridge
